// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

using Stride.Rendering.Data;
using Stride.Rendering.Materials;
namespace StrideEdExt.Rendering
{
    internal static partial class ShaderMixins
    {
        internal partial class PaintingStrideBaseEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "ShaderBase");
                context.Mixin(mixin, "TransformationBase");
                context.Mixin(mixin, "NormalStream");
                var extensionTessellationShader = context.GetParam(MaterialKeys.TessellationShader);
                if (context.GetParam(StrideEffectBaseKeys.HasInstancing))
                {
                    mixin.AddMacro("ModelTransformUsage", context.GetParam(StrideEffectBaseKeys.ModelTransformUsage));
                    context.Mixin(mixin, "TransformationWAndVPInstanced");
                    if (context.GetParam(MaterialKeys.HasNormalMap))
                    {
                        if (extensionTessellationShader != null)
                        {
                            context.Mixin(mixin, "NormalFromNormalMappingTessellationInstanced");
                        }
                        else
                        {
                            context.Mixin(mixin, "NormalFromNormalMappingInstanced");
                        }
                    }
                    else
                    {
                        context.Mixin(mixin, "NormalFromMeshInstanced");
                    }
                }
                else
                {
                    context.Mixin(mixin, "TransformationWAndVP");
                    if (context.GetParam(MaterialKeys.HasNormalMap))
                    {
                        if (extensionTessellationShader != null)
                        {
                            context.Mixin(mixin, "NormalFromNormalMappingTessellation");
                        }
                        else
                        {
                            context.Mixin(mixin, "NormalFromNormalMapping");
                        }
                    }
                    else
                    {
                        context.Mixin(mixin, "NormalFromMesh");
                    }
                }
                if (context.GetParam(MaterialKeys.HasSkinningPosition))
                {
                    mixin.AddMacro("SkinningMaxBones", context.GetParam(MaterialKeys.SkinningMaxBones));
                    if (context.GetParam(StrideEffectBaseKeys.HasInstancing))
                    {
                        context.Mixin(mixin, "TransformationSkinningInstanced");
                    }
                    else
                    {
                        context.Mixin(mixin, "TransformationSkinning");
                    }
                    if (context.GetParam(MaterialKeys.HasSkinningNormal))
                    {
                        context.Mixin(mixin, "NormalMeshSkinning");
                    }
                    if (context.GetParam(MaterialKeys.HasSkinningTangent))
                    {
                        context.Mixin(mixin, "TangentMeshSkinning");
                    }
                    if (context.GetParam(MaterialKeys.HasSkinningNormal))
                    {
                        if (context.GetParam(MaterialKeys.HasNormalMap))
                        {
                            if (extensionTessellationShader != null)
                            {
                                context.Mixin(mixin, "NormalVSSkinningNormalMappingTessellation");
                            }
                            else
                            {
                                context.Mixin(mixin, "NormalVSSkinningNormalMapping");
                            }
                        }
                        else
                        {
                            context.Mixin(mixin, "NormalVSSkinningFromMesh");
                        }
                    }
                }
            }

            [System.Runtime.CompilerServices.ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("PaintingStrideBaseEffect", new PaintingStrideBaseEffect());
            }
        }
    }
}
