// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideEdExt.Rendering
{
    public static partial class MaterialTerrainEditPreviewDiffuseMapKeys
    {
        public static readonly ObjectParameterKey<Texture> TerrainMaterialWeightMap = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> EditLayerMaterialWeightMap = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<Vector2> TerrainMaterialWeightMapSize = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<uint> OverrideMaterialIndex = ParameterKeys.NewValue<uint>();
        public static readonly ValueParameterKey<uint> MaterialMapPaintModeType = ParameterKeys.NewValue<uint>();
    }
}
