// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideEdExt.Rendering
{
    public static partial class MaterialTerrainDiffuseMapKeys
    {
        public static readonly ObjectParameterKey<Texture> MaterialIndexMap = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> DiffuseMap = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> NormalMap = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> HeightBlendMap = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<Vector2> MaterialIndexMapSize = ParameterKeys.NewValue<Vector2>();
        public static readonly ObjectParameterKey<SamplerState> MaterialIndexMapSampler = ParameterKeys.NewObject<SamplerState>();
    }
}
