// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace StrideEdExt.Rendering
{
    public static partial class MaterialTerrainEditPreviewHeightmapKeys
    {
        public static readonly ObjectParameterKey<Texture> TerrainHeightmap = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<Vector2> TerrainHeightmapSize = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector2> TerrainHeightRange = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<float> MaxAdjustmentHeightValue = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<Vector3> InitialBrushWorldPosition = ParameterKeys.NewValue<Vector3>();
        public static readonly ValueParameterKey<uint> HeightmapPaintModeType = ParameterKeys.NewValue<uint>();
        public static readonly ObjectParameterKey<SamplerState> TerrainHeightmapTextureSampler = ParameterKeys.NewObject<SamplerState>();
    }
}
