// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

using Stride.Rendering.Data;
using Stride.Shaders.Compiler;
namespace SceneEditorExtensionExample.Rendering
{
    internal static partial class ShaderMixins
    {
        internal partial class HeightmapRenderEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "ShaderBase");
                if (context.GetParam(StrideEffectBaseKeys.HasInstancing))
                {
                    mixin.AddMacro("ModelTransformUsage", context.GetParam(StrideEffectBaseKeys.ModelTransformUsage));
                    context.Mixin(mixin, "TransformationWAndVPInstanced");
                }
                else
                {
                    context.Mixin(mixin, "TransformationWAndVP");
                }
                context.Mixin(mixin, "HeightmapRenderShader");
            }

            [System.Runtime.CompilerServices.ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("HeightmapRenderEffect", new HeightmapRenderEffect());
            }
        }
    }
}
